package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.MascaraMoeda;
import model.bean.Servico;
import model.dao.ServicoDAO;

/**
 *
 * @author lopea
 */
public class AlterarServico extends javax.swing.JFrame {

    Servico s2 = new Servico();

    /**
     * Creates new form AlterarProduto
     */
    public AlterarServico() {
        try {
            initComponents();
//                txtValor.setDocument(new MascaraMoeda.MonetarioDocument());
            Color cor = new Color(219, 219, 112);
            getContentPane().setBackground(cor);
            txtDescricao.setLineWrap(true);
//            txtTeste = new JFormattedTextField(8);

            for (Servico s : ServicoDAO.readId(Servico.getId_pesquisa())) {

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//                String calendario = sdf.format(txtJCalendar.getDate());
                Date data = (Date) sdf.parse(s.getData_servico());
//                ServicoDAO.readId(Servico.getId_pesquisa());
                txtNumeroServico.setText(Integer.toString(s.getId()));
                txtNomeEmpresa.setText(s.getNome_empresa());
                txtBairro.setText(s.getBairro());
                txtCelular.setText(s.getCelular());
                txtComplemento.setText(s.getComplemento());
                txtJCalendar.setDate(sdf.parse(s.getData_servico()));
                txtDescricao.setText(s.getDescricao());
                txtEndereco.setText(s.getRua());
                txtNumero.setText(s.getNumero());
                txtReferencia.setText(s.getReferencia());
                txtTelefone.setText(s.getTelefone());
                txtValor.setText(s.getValor());
                txtNomeResponsavel.setText(s.getNome_responsavel());
//                    s.getNome()
//                ,
//                    s.getQtd()
//                ,
//                    s.getValidade()
//                ,
//                    s.getPreco()
            }//        readJTable();
        } catch (ParseException ex) {
            Logger.getLogger(AlterarServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNumeroServico.setEditable(false);

        //        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
//        jTProdutos.setRowSorter(new TableRowSorter(modelo));
//        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/box32.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNomeResponsavel = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnAtualizar = new javax.swing.JButton();
        txtJCalendar = new com.toedter.calendar.JDateChooser();
        lblMensagem = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Nome da Empresa");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Nome do Responsável");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Bairro");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Referência");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Nº");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Endereço");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Celular");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Telefone");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Complemento");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Descrição");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Data do Serviço");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Valor do Serviço");

        txtNomeEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNomeResponsavel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtComplemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtReferencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nº do Serviço ");

        txtNumeroServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nvo loping.jpeg"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane3.setViewportView(txtDescricao);

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-selecionado-30 (1).png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        txtJCalendar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtJCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJCalendarMouseClicked(evt);
            }
        });

        lblMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("R$");

        txtValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtValorMouseExited(evt);
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-retornar-30.png"))); // NOI18N
        btnVoltar.setMaximumSize(new java.awt.Dimension(89, 23));
        btnVoltar.setMinimumSize(new java.awt.Dimension(89, 23));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("*");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("*");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("*");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("*");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("*");

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("*");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(txtNumeroServico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel30)))
                        .addGap(4, 4, 4)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel31)
                        .addGap(13, 13, 13)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel28)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel32)
                        .addGap(12, 12, 12)
                        .addComponent(txtJCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel29)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel33)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel27)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel22))
                    .addComponent(jLabel20)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel21))
                    .addComponent(jLabel30)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel17))
                    .addComponent(jLabel31)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel28))
                    .addComponent(jLabel32)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtJCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel27))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Servico s = new Servico();
        if (txtNomeResponsavel.getText().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else if (txtEndereco.getText().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else if (txtNumero.getText().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else if (txtBairro.getText().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else if (txtJCalendar.getDate().toString().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else if (txtValor.getText().isEmpty()) {
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("<html><b>Por favor prencha os campos com (*) </b></html>");
        } else {

            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String calendario = (String) sdf.format(txtJCalendar.getDate());

                /*Verifico se o usuario digitou , no valor*/
                if (txtValor.getText().toLowerCase().contains(",")) {

                    String novoValor = txtValor.getText().replace(',', '.');
                    s.setId(Integer.parseInt(txtNumeroServico.getText().trim()));
                    s.setNome_empresa(txtNomeEmpresa.getText().trim());
                    s.setNome_responsavel(txtNomeResponsavel.getText().trim());
                    s.setTelefone(txtTelefone.getText().trim());
                    s.setCelular(txtCelular.getText().trim());
                    s.setRua(txtEndereco.getText().trim());
                    s.setNumero(txtNumero.getText().trim());
                    s.setBairro(txtBairro.getText().trim());
                    s.setComplemento(txtComplemento.getText().trim());
                    s.setReferencia(txtReferencia.getText().trim());
                    s.setData_servico(calendario.trim());
                    s.setDescricao(txtDescricao.getText().trim());
                    s.setValor(novoValor.trim());

                    ServicoDAO.update(s);
                    JOptionPane.showMessageDialog(null, "<html><font color=#0E6B19>" + s.getMensagem() + "</font></html>");
//                    ConsultaServico novaTela = new ConsultaServico();
                    
                    dispose();
//                    dispose();

                    for (Servico s2 : ServicoDAO.readId(Servico.getId_pesquisa())) {

//                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//                String calendario = sdf.format(txtJCalendar.getDate());
                        Date data = (Date) sdf.parse(s2.getData_servico());
//                ServicoDAO.readId(Servico.getId_pesquisa());
                        txtNumeroServico.setText(Integer.toString(s2.getId()));
                        txtNomeEmpresa.setText(s2.getNome_empresa());
                        txtBairro.setText(s2.getBairro());
                        txtCelular.setText(s2.getCelular());
                        txtComplemento.setText(s2.getComplemento());
                        txtJCalendar.setDate(data);
                        txtDescricao.setText(s2.getDescricao());
                        txtEndereco.setText(s2.getRua());
                        txtNumero.setText(s2.getNumero());
                        txtReferencia.setText(s2.getReferencia());
                        txtTelefone.setText(s2.getTelefone());
                        txtValor.setText(s2.getValor());
                        txtNomeResponsavel.setText(s2.getNome_responsavel());

//                    s.getNome()
//                ,
//                    s.getQtd()
//                ,
//                    s.getValidade()
//                ,
//                    s.getPreco()
                    }//
                    /*Limpa os campos*/
//                txtNomeEmpresa.setText("");
//                txtNomeResponsavel.setText("");
//                txtTelefone.setText("");
//                txtValor.setText("");
//                txtEndereco.setText("");
//                txtNumero.setText("");
//                txtBairro.setText("");
//                txtComplemento.setText("");
//                txtReferencia.setText("");
//                txtJCalendar.setDateFormatString("");
//                txtDescricao.setText("");
                } else {
                    s.setId(Integer.parseInt(txtNumeroServico.getText().trim()));
                    s.setNome_empresa(txtNomeEmpresa.getText().trim());
                    s.setNome_responsavel(txtNomeResponsavel.getText().trim());
                    s.setTelefone(txtTelefone.getText().trim());
                    s.setCelular(txtCelular.getText().trim());
                    s.setRua(txtEndereco.getText().trim());
                    s.setNumero(txtNumero.getText().trim());
                    s.setBairro(txtBairro.getText().trim());
                    s.setComplemento(txtComplemento.getText().trim());
                    s.setReferencia(txtReferencia.getText().trim());
                    s.setData_servico(calendario.trim());
                    s.setValor(txtValor.getText().trim());
                    s.setDescricao(txtDescricao.getText().trim());

                    ServicoDAO.update(s);
//
////                lblMensagem.setForeground(Color.);
////                lblMensagem.setText("<html><font color=#0E6B19>" + s.getMensagem() + "</font></html>");
                    JOptionPane.showMessageDialog(null, "<html><font color=#0E6B19>" + s.getMensagem() + "</font></html>");
//                    ConsultaServico novaTela = new ConsultaServico();
//                    novaTela.readJTable();
                    dispose();

                    for (Servico s2 : ServicoDAO.readId(Servico.getId_pesquisa())) {

//                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//                String calendario = sdf.format(txtJCalendar.getDate());
                        Date data = (Date) sdf.parse(s2.getData_servico());
//                ServicoDAO.readId(Servico.getId_pesquisa());
                        txtNumeroServico.setText(Integer.toString(s2.getId()));
                        txtNomeEmpresa.setText(s2.getNome_empresa());
                        txtBairro.setText(s2.getBairro());
                        txtCelular.setText(s2.getCelular());
                        txtComplemento.setText(s2.getComplemento());
                        txtJCalendar.setDate(data);
                        txtDescricao.setText(s2.getDescricao());
                        txtEndereco.setText(s2.getRua());
                        txtNumero.setText(s2.getNumero());
                        txtReferencia.setText(s2.getReferencia());
                        txtTelefone.setText(s2.getTelefone());
                        txtValor.setText(s2.getValor());
                        txtNomeResponsavel.setText(s2.getNome_responsavel());

//                    s.getNome()
//                ,
//                    s.getQtd()
//                ,
//                    s.getValidade()
//                ,
//                    s.getPreco()
                    }//
                    /*Limpa os campos*/
//                txtNomeEmpresa.setText("");
//                txtNomeResponsavel.setText("");
//                txtTelefone.setText("");
//                txtValor.setText("");
//                txtEndereco.setText("");
//                txtNumero.setText("");
//                txtBairro.setText("");
//                txtComplemento.setText("");
//                txtReferencia.setText("");
//                txtJCalendar.setDateFormatString("");
//                txtDescricao.setText("");
                }
            } catch (ParseException ex) {
                Logger.getLogger(AlterarServico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtJCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJCalendarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJCalendarMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
//        ConsultaServico novaTela = new ConsultaServico();
//        novaTela.setVisible(true);
        dispose();
        //        try {
        //            novaTela = new TelaOpcoes();
        //        } catch (SQLException ex) {
        //            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        //        novaTela.setVisible(true);
        //        dispose();
        //
        //        if (enviatexto == null) {
        //            try {
        //                enviatexto = new TelaOpcoes();
        //            } catch (SQLException ex) {
        //                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        //            }
        //            enviatexto.setVisible(true);
        //            setDefaultCloseOperation(TelaLogin.HIDE_ON_CLOSE);
        ////            setDefaultCloseOperation(enviatexto.HIDE_ON_CLOSE);
        //
        //            try {
        //                enviatexto.recebendo(getLogin(), new String(getSenha()));
        //            } catch (SQLException ex) {
        //                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        //            }
        //        } else {
        //            enviatexto.setVisible(true);
        //            enviatexto.setState(TelaOpcoes.NORMAL);
        //            setDefaultCloseOperation(TelaLogin.HIDE_ON_CLOSE);
        ////            setDefaultCloseOperation(enviatexto.HIDE_ON_CLOSE);
        //
        //            try {
        //                enviatexto.recebendo(getLogin(), new String(getSenha()));
        //            } catch (SQLException ex) {
        //                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        //            }
        //        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnVoltar.doClick();

        }
    }//GEN-LAST:event_btnVoltarKeyPressed

    private void txtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorMouseClicked
        s2.setValor(txtValor.getText());
        txtValor.setDocument(new MascaraMoeda.MonetarioDocument());
    }//GEN-LAST:event_txtValorMouseClicked

    private void txtValorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEndereco;
    private com.toedter.calendar.JDateChooser txtJCalendar;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtNomeResponsavel;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroServico;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
//public void recebendo(String login, String senha) throws SQLException {
//        setLogin(login);
//        setSenha(senha);
//        UsuarioDAO dao = new UsuarioDAO();
////        lblBemVindo.setText("Olá " + dao.pesquisaNome(dao.pesquisaId(login, senha)) + ", seja bem vindo(a)!");
//        setNome(dao.pesquisaNome(dao.pesquisaId(login, senha)));
//    }
}
